### ISSUE TITLE
Not opening 

### ISSUE THREAD

**Issue by dassagar57** [txthinking/wiresharkhelper#1]
The application not opening on windows

**Comment by txthinking** [comment]
Did you run it in GitBash?

**Comment by romestylez** [comment]
Can you please say what to download and run in GitBash ?

Tried wiresharkhelper_darwin_amd64 but get 

bash: ./wiresharkhelper_darwin_amd64: cannot execute binary file: Exec format error

**Comment by txthinking** [comment]
Darwin is for macos.

You can do this:

1. Open gitbash
2. $ bash <(curl https://bash.ooo/nami.sh)
3. $ nami install wiresharkhelper
4. $ wiresharkhelper DESKTOP_LAN_IP

**Comment by txthinking** [comment]
Here is a video

https://youtu.be/CioIqzSlXl8

**Comment by romestylez** [comment]
Got it installed and running. Can download the profile on my iphone via ip:8888 but when entering ip:9999 in the wiresharhelper on my iphone it trys to connect but the nothing happens.

When i try to open ip:9999 via safari i can see "wrong version" in the GitBash. Sad thought its working ;(

**Comment by txthinking** [comment]
And this video: https://www.youtube.com/watch?v=szzMg-Uugjo

**Comment by txthinking** [comment]
You can also join the private telegram group, you can find the link in app.
